backend/accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

backend/djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from todos.views import TodosHomeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("todos/", include("todos.urls")),
    path("", TodosHomeView.as_view(), name="home"),
]

backend/todos/urls.py
from django.urls import path

from .views import TodosHomeView, TodosCreateView, TodosEditView, todo_delete, todo_change_status

urlpatterns = [
    path("", TodosHomeView.as_view(), name="home"), 
    path("create/", TodosCreateView.as_view(), name="todos_create"),
    path("<int:pk>/edit/", TodosEditView.as_view(), name="todos_edit"),
    path("<int:todo_id>/delete/", todo_delete, name="todo_delete"),
    path("<int:todo_id>/change_status/<str:status>", todo_change_status, name="todo_change_status"),
]

backend/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    pass

backend/todos/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


# Create your models here.
class Todo(models.Model):
    TAG_CHOICES = [
        ('Personal', 'Personal'),
        ('Work', 'Work'),
        ('School', 'School'),
        ('Coding', 'Coding'),
    ]

    tag = models.CharField(max_length=10, choices=TAG_CHOICES, default='Personal')
    title = models.CharField(max_length=90)
    description = models.TextField(blank=True)
    status = models.CharField(max_length=20)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("home")
    
    @property
    def tag_color(self):
        tag_colors = {  
            "Personal": "#7875A9",
            "Work": "#7DA9D6",
            "School": "#FF8E8E",
            "Coding": "#7BC683",
        }
        return tag_colors.get(self.tag, '#000000')  # default color if tag not found

backend/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = UserCreationForm.Meta.fields


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields

backend/todos/forms.py
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ['title', 'description', 'tag']
        widgets = {
            'tag': forms.RadioSelect
        }

backend/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CustomUserCreationForm


# Create your views here.
class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

backend/todos/views.py
from django.shortcuts import render
from django.views.generic import ListView, UpdateView, View
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render, redirect

from .forms import TodoForm
from .models import Todo


# Create your views here.
class TodosHomeView(LoginRequiredMixin, ListView):
    model = Todo
    template_name = "home.html"

class TodosCreateView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, "todos_create.html")

    def post(self, request, *args, **kwargs):
        form = TodoForm(request.POST)
        if form.is_valid():
            print("form is valid")
            todo = form.save(commit=False)
            todo.author = request.user
            todo.status = "todo"
            todo.save()
            return redirect('home')
        return render(request, 'todos_create.html', {'form': form})


class TodosEditView(LoginRequiredMixin, UpdateView):
    model = Todo
    fields = (
        "title",
        "description",
        "tag",
    )

    tag_colors = {  
    "Personal": "#7875A9",
    "Work": "#7DA9D6",
    "School": "#FF8E8E",
    "Coding": "#7BC683",
    }
    template_name = "todos_edit.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag_color'] = self.tag_colors.get(self.object.tag, '#000000')  # default color if tag not found
        return context


@login_required
@require_POST
def todo_delete(request, todo_id):
    todo = get_object_or_404(Todo, id=todo_id)
    todo.delete()
    return redirect('home')


@login_required
@require_POST
def todo_change_status(request, todo_id, status):
    todo = get_object_or_404(Todo, id=todo_id)
    todo.status = status
    todo.save()
    return redirect('home')

backend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} DoIt! {% endblock title %}</title>
</head>
<body>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
</body>
</html>

backend/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DoIt!</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <link rel="icon" type="png" href="{% static 'img/doit-removebg-preview.png' %}">
    <!-- Font Awesome Cdn Link -->
    <script src="https://kit.fontawesome.com/04558dcba4.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="sidebar">
        <div class="logo">
            <h2><img src="{% static 'img/doit-removebg-preview.png' %}" class="logoimg"><span>DoIt!</span></h2>
        </div>
        <ul class="menu">
            <li class="dash active">
                <a href="#">
                    <i class="fas fa-user"></i>
                    <span>Home</span>
                </a>
            </li>
            <li class="personal" id="personal" draggable="true">
                <a href="#">
                    <i class="fas fa-clipboard"></i>
                    <span>Personal</span>
                </a>
            </li>
            <li class="work">
                <a href="#">
                    <i class="fas fa-folder-open"></i>
                    <span>Work</span>
                </a>
            </li>
            <li class="school">
                <a href="#">
                    <i class="fas fa-book"></i>
                    <span>School</span>
                </a>
            </li>
            <li class="coding">
                <a href="#">
                    <i class="fas fa-laptop-code"></i>
                    <span>Coding</span>
                </a>
            </li>
            {% if user.is_authenticated %}
            <li class="logout auth">
                <a href="{% url 'logout' %}">
                    <i class="fa-solid fa-arrow-right-from-bracket"></i>
                    <span>Log out</span>
                </a>
            </li>
            {% else %}
            <li class="login auth">
                <a href="{% url 'login' %}">
                    <i class="fa-solid fa-arrow-right-to-bracket"></i>
                    <span>Log In </span>
                </a>
            </li>
            <li class="signup auth">
                <a href="{% url 'signup' %}">
                    <i class="fa-solid fa-user-plus fa-2xs"></i>
                    <span>Sign Up </span>
                </a>
            {% endif %}
        </ul>
    </div>

    <!-- main sa right -->
    <div class="main">
        <div class="header-wrapper">
            <div class="header-title">
                {% if user.is_authenticated %}
                <h2>Hello, {{ user.username }}</h2>
                {% else %}
                <h2>You are not logged in</h2>
                {% endif %}
            </div>
            <img src="{% static 'img/rimuru.jpg' %}" alt="">
        </div>
   
        <!-- BUTTON PARA SA ADD -->
        <a href="{% url 'todos_create' %}">
            <div class="addBox">
                <i class="fa-solid fa-plus"></i>
                <p>Add Task</p>
            </div>
        </a>

        <div class="kanban-board">
            <!-- To Do Column -->
            <div class="kanban-column" id="todo-column">
                <h5>To do</h5>
                <div class="kanban-cards" id="todo-cards">
                    {% for todo in todo_list %}
                    {% if todo.status == "todo" and user == todo.author %} 
                    <div class="kanban-card" id="{{ todo.id }}" data-tag="{{ todo.tag }}">
                        <h4>
                            {{ todo.title }}
                            <div class="icons">
                                <a href="{% url 'todos_edit' todo.id %}">
                                    <i class="fas fa-edit edit-icon" onclick="window.location.href='#'"></i> 
                                </a>
                                <form method="POST" action="{% url 'todo_delete' todo.id %}" class="form-delete">
                                    {% csrf_token %}
                                    <button type="submit">
                                        <i class="fas fa-trash-alt delete-icon" onclick="window.location.href='#'"></i>
                                    </button>
                                </form>
                            </div>
                        </h4>
                        <p>{{ todo.description }}</p>
                        <div class="kanban-card-lower-part">
                            <div class="kanban-card-tag" style="background-color: {{ todo.tag_color }}">
                                {{ todo.tag}}
                            </div>

                            <div class="icons">
                                <form method="POST" action="{% url 'todo_change_status' todo.id 'inprogress' %}" class="form-delete">
                                    {% csrf_token %}
                                    <button type="submit">
                                        <i class="fa-solid fa-arrow-right"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}    
                </div>
            </div>
            <!-- In Progress Column -->
            <div class="kanban-column in-progress" id="inprogress-column">
                <h5>In progress </h5>
                <div class="kanban-cards" id="inprogress-cards">
                    {% for todo in todo_list %}
                    {% if todo.status == "inprogress" and user == todo.author %}
                    <div class="kanban-card" id="{{ todo.id }}" data-tag="{{ todo.tag }}">
                        <h4>
                            {{ todo.title }}
                            <div class="icons">
                                <a href="{% url 'todos_edit' todo.id %}">
                                    <i class="fas fa-edit edit-icon" onclick="window.location.href='#'"></i> 
                                </a>
                                <form method="POST" action="{% url 'todo_delete' todo.id %}" class="form-delete">
                                    {% csrf_token %}
                                    <button type="submit">
                                        <i class="fas fa-trash-alt delete-icon" onclick="window.location.href='#'"></i>
                                    </button>
                                </form>
                            </div>
                        </h4>
                        <p>{{ todo.description }}</p>
                        <div class="kanban-card-lower-part">
                            <div class="kanban-card-tag" style="background-color: {{ todo.tag_color }}">
                                {{ todo.tag }}
                            </div>

                            <div class="icons">
                                <form method="POST" action="{% url 'todo_change_status' todo.id 'todo' %}" class="form-delete">
                                    {% csrf_token %}
                                    <button type="submit">
                                        <i class="fa-solid fa-arrow-left"></i>
                                    </button>
                                </form>
                                <form method="POST" action="{% url 'todo_change_status' todo.id 'completed' %}" class="form-delete">
                                    {% csrf_token %}
                                    <button type="submit">
                                        <i class="fa-solid fa-arrow-right"></i>
                                    </button>
                                </form>                            
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
            <!-- Completed Column -->
            <div class="kanban-column" id="completed-column">
                <h5>Completed</h5>
                <div class="kanban-cards" id="completed-cards">
                    {% for todo in todo_list %}
                    {% if todo.status == "completed" and user == todo.author %}
                    <div class="kanban-card completed-card" id="{{ todo.id }}" data-tag="{{ todo.tag }}">
                        <h4>
                            {{ todo.title }}
                            <div class="icons">
                                <a href="{% url 'todos_edit' todo.id %}">
                                    <i class="fas fa-edit edit-icon" onclick="window.location.href='#'"></i> 
                                </a>                                
                                <form method="POST" action="{% url 'todo_delete' todo.id %}" class="form-delete">
                                    {% csrf_token %}
                                    <button type="submit">
                                        <i class="fas fa-trash-alt delete-icon" onclick="window.location.href='#'"></i>
                                    </button>
                                </form>
                            </div>
                        </h4>
                        <p>{{ todo.description }}</p>
                        <div class="kanban-card-lower-part">
                            <div class="kanban-card-tag" style="background-color: {{ todo.tag_color }}">
                                {{ todo.tag }}
                            </div>

                            <div class="icons">
                                <form method="POST" action="{% url 'todo_change_status' todo.id 'inprogress' %}" class="form-delete">
                                    {% csrf_token %}
                                    <button type="submit">
                                        <i class="fa-solid fa-arrow-left"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'script.js' %}"></script>
</body>
</html>

backend/templates/todos_create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DoIt</title>
    <link rel="stylesheet" type="text/css" href="{% static 'todos_create.css' %}">
    <link rel="icon" type="png" href="{% static 'img/doit-removebg-preview.png' %}">
    <!-- Font Awesome Cdn Link -->
    <script src="https://kit.fontawesome.com/04558dcba4.js" crossorigin="anonymous"></script>
</head>
<body>
    <!-- new task -->
    <div class="popup-box">
        <div class="popup">
            <div class="content">
                <header>
                    <p>New Task</p>
                    <a href="{% url 'home' %}">
                        <i class="fa-solid fa-circle-xmark"></i>
                    </a>
                </header>
                <form method="POST">
                    {% csrf_token %}
                    <!-- {{ form.as_p }} -->
                    <div class="row title">
                        <label for="title">Title</label>
                        <input type="text" id="title" placeholder="Enter your to-do here" name="title">
                    </div>
                    <div class="row description">
                        <label for="desc">Description</label>
                        <textarea id="desc" placeholder="Provide additional details..." name="description"></textarea>
                    </div>
                    <div class="row dropdown">
                        <label>Tags</label>
                        <div class="btn-radio" id="radio">
                            <input type="radio" id="radio01" name="tag" value="Personal">
                            <label for="radio01">
                                <span><i class="fas fa-clipboard"></i>Personal</span></label>
                        </div>
                        <div class="btn-radio">
                            <input type="radio" id="radio02" name="tag" value="Work">
                            <label for="radio02"><span><i class="fas fa-folder-open"></i>Work</span></label>
                        </div>
                        <div class="btn-radio">
                            <input type="radio" id="radio03" name="tag" value="School">
                            <label for="radio03"><span><i class="fas fa-book"></i>School</span></label>
                        </div>
                        <div class="btn-radio">
                            <input type="radio" id="radio04" name="tag" value="Coding">
                            <label for="radio04"><span><i class="fas fa-laptop-code"></i>Coding</span></label>
                        </div>
                    </div>
                    <button><input type="submit" value="Add Task"></button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

backend/templates/todos_edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DoIt</title>
    <link rel="stylesheet" type="text/css" href="{% static 'todos_edit.css' %}">
    <link rel="icon" type="png" href="{% static 'img/doit-removebg-preview.png' %}">
    <!-- Font Awesome Cdn Link -->
    <script src="https://kit.fontawesome.com/04558dcba4.js" crossorigin="anonymous"></script>
</head>
<body>
    <!-- Edit Task Popup -->
    <div class="popup-box edit-popup">
        <div class="popup">
            <div class="content">
                <header>
                    <p>Edit Task</p>
                    <a href="{% url 'home' %}">
                        <i class="fa-solid fa-circle-xmark close-edit-popup"></i>
                    </a>
                </header>
                <form method="POST">
                    {% csrf_token %}
                    <!-- {{ form.as_p }} -->
                    <div class="row title">
                        <label for="edit-title">Title</label>
                        <input id="edit-title" name="title" value="{{ todo.title }}">
                    </div>
                    <div class="row description">
                        <label for="edit-desc">Description</label>
                        <textarea id="edit-desc" name="description">{{ todo.description }}</textarea>
                    </div>
                    <div class="row dropdown">
                        <label>Tags</label>
                        <div class="btn-radio" id="edit-radio">
                            <div class="btn-radio">
                                <input type="radio" id="edit-radio01" name="tag" value="Personal" {% if todo.tag == "Personal" %}checked{% endif %} />
                                <label for="edit-radio01"><span><i class="fas fa-clipboard"></i>Personal</span></label>
                            </div>
                            <div class="btn-radio">
                                <input type="radio" id="edit-radio02" name="tag" value="Work" {% if todo.tag == "Work" %}checked{% endif %} />
                                <label for="edit-radio02"><span><i class="fas fa-folder-open"></i>Work</span></label>
                            </div>
                            <div class="btn-radio">
                                <input type="radio" id="edit-radio03" name="tag" value="School" {% if todo.tag == "School" %}checked{% endif %} />
                                <label for="edit-radio03"><span><i class="fas fa-book"></i>School</span></label>
                            </div>
                            <div class="btn-radio">
                                <input type="radio" id="edit-radio04" name="tag" value="Coding" {% if todo.tag == "Coding" %}checked{% endif %} />
                                <label for="edit-radio04"><span><i class="fas fa-laptop-code"></i>Coding</span></label>
                            </div>
                        </div>
                    </div>
                    <button><input type="submit" value="Update Task"></button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>